#!/usr/bin/env ruby

require_relative 'lib/parse_arguments'

command = ARGV[0]
options = ParseArguments.parse
options[:name] = ARGV[1]
error_messages = ParseArguments.validate(options)

if error_messages.empty?
	puts "Theoretically creating: a film named #{options[:name]}, released in #{options[:year]} and directed by #{options[:director]} from #{options[:country]}."
else
  puts error_messages
end